# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-22 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date_contact',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 19, 50, 49, 864666, tzinfo=utc)),
        ),
    ]
