# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180922_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date_contact',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
